export const API_REQUEST = 'API_REQUEST'
export const TOGGLE_LOADER = 'TOGGLE_LOADER'

export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER = 'UPDATE_USER'

export const SET_PREFERENCES = 'SET_PREFERENCES'
export const ADD_PREFERENCE = 'ADD_PREFERENCE'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'

export const SET_RESTAURANTS = 'SET_RESTAURANTS'
export const ADD_RESTAURANT = 'ADD_RESTAURANT'
export const SET_CURRENT_RESTAURANT = 'SET_CURRENT_RESTAURANT'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const ADD_MENU_ITEM = 'ADD_MENU_ITEM'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const REMOVE_ALL = 'REMOVE_ALL'
export const UPDATE_CART = 'UPDATE_CART'

export const NLP_REQUEST = 'NLP_REQUEST'

export const SUGGEST_CALORIES = "SUGGEST_CALORIES"
export const SET_TO_ZERO = "SET_TO_ZERO"